//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Femalab.Model.Persistence
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERSONA
    {
        public string DNI { get; set; }
        public string APE_PATERNO { get; set; }
        public string APE_MATERNO { get; set; }
        public string NOMBRES { get; set; }
        public string SEXO { get; set; }
        public string FECHA_NACIMIENTO { get; set; }
        public string UBIGEO_CODIGO { get; set; }
        public string UBIGEO_DIRECCION { get; set; }
    }
}
